import { NavbarTop } from "./components/Header/NavbarTop";
import { NotificationComponent } from "./components/Notification/notificationComponent";
import AppContextProvider from "./context/AppContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppContextProvider>
      <html lang="pt-br">
        <body className={inter.className + " text-white"}>
        <NotificationComponent />

          <NavbarTop />
          {children}
        </body>
      </html>
    </AppContextProvider>
  );
}
